/**
 * Types for the Codex API. These can be autogenerated from the GraphQL schema
 * in the future.
 *
 * https://graph.codex.io/schema/latest.graphql
 */
export type CodexPrice = {
  address: string;
  priceUsd: number;
};

export type CodexToken = {
  address: string;
  networkId?: number | null;
  name: string | null;
  symbol: string | null;
  decimals: number;
  info: { imageThumbUrl: string | null } | null;
};

export type CodexTokenBars = {
  /** Timestamp of the bar in seconds */
  t: number[];
  /** Closing price of the bar */
  c: (number | null)[];
};
